name: Publish package

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build-linux:
    name: Build distributions (Linux)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install project dependencies
        run: uv sync --no-dev
        shell: bash

      - name: Build package
        run: uv build
        shell: bash

      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

      - name: Publish package distributions to PyPI (Trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
