name: Publish package

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build distributions (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        shell: pwsh

      - name: Install Poetry
        run: python -m pip install --upgrade poetry
        shell: pwsh

      - name: Install project dependencies (no dev)
        run: poetry install --no-dev
        shell: pwsh

      - name: Build package
        run: poetry build
        shell: pwsh

      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-windows
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact

      - name: Publish package distributions to PyPI (Trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/