name: Publish package

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build-linux:
    name: Build distributions (Linux)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        shell: bash

      - name: Install Poetry
        run: python -m pip install --upgrade poetry
        shell: bash

      - name: Install project dependencies
        run: poetry install --without dev
        shell: bash

      - name: Build package
        run: poetry build
        shell: bash

      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

      - name: Publish package distributions to PyPI (Trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
